services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bill_local_django
    container_name: bill_local_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - '8000:8000'
    command: /start


